import type { SeoLocale } from "@/lib/seo";

/**
 * Country names in Spanish.
 *
 * The datasets are English, so a Spanish page would otherwise say
 * "Nacionalidad: Spain" — the kind of half-translated detail that makes a
 * page read like it was run through a machine. Only the countries the two
 * datasets actually contain are listed; anything else falls through to the
 * English name, which is better than a blank.
 */
const NATION_ES: Record<string, string> = {
  Albania: "Albania",
  Algeria: "Argelia",
  Angola: "Angola",
  Argentina: "Argentina",
  Armenia: "Armenia",
  Australia: "Australia",
  Austria: "Austria",
  Azerbaijan: "Azerbaiyán",
  Belgium: "Bélgica",
  Bolivia: "Bolivia",
  "Bosnia and Herzegovina": "Bosnia y Herzegovina",
  Brazil: "Brasil",
  "Burkina Faso": "Burkina Faso",
  Burundi: "Burundi",
  "Cabo Verde": "Cabo Verde",
  Cameroon: "Camerún",
  Canada: "Canadá",
  "Cape Verde": "Cabo Verde",
  Chile: "Chile",
  Colombia: "Colombia",
  Comoros: "Comoras",
  "Congo DR": "RD del Congo",
  "Costa Rica": "Costa Rica",
  Croatia: "Croacia",
  Czechia: "Chequia",
  "Côte d'Ivoire": "Costa de Marfil",
  Denmark: "Dinamarca",
  Ecuador: "Ecuador",
  Egypt: "Egipto",
  England: "Inglaterra",
  "Equatorial Guinea": "Guinea Ecuatorial",
  Estonia: "Estonia",
  Finland: "Finlandia",
  France: "Francia",
  Gabon: "Gabón",
  Gambia: "Gambia",
  Georgia: "Georgia",
  Germany: "Alemania",
  Ghana: "Ghana",
  Greece: "Grecia",
  Guinea: "Guinea",
  "Guinea-Bissau": "Guinea-Bisáu",
  Hungary: "Hungría",
  Iceland: "Islandia",
  Indonesia: "Indonesia",
  Israel: "Israel",
  Italy: "Italia",
  Japan: "Japón",
  "Korea Republic": "Corea del Sur",
  Kosovo: "Kosovo",
  Liberia: "Liberia",
  Lithuania: "Lituania",
  Luxembourg: "Luxemburgo",
  Mali: "Malí",
  Mexico: "México",
  Montenegro: "Montenegro",
  Morocco: "Marruecos",
  Mozambique: "Mozambique",
  Netherlands: "Países Bajos",
  "New Zealand": "Nueva Zelanda",
  Nigeria: "Nigeria",
  "Northern Ireland": "Irlanda del Norte",
  Norway: "Noruega",
  Paraguay: "Paraguay",
  Peru: "Perú",
  Poland: "Polonia",
  Portugal: "Portugal",
  "Republic of Ireland": "Irlanda",
  Romania: "Rumanía",
  Russia: "Rusia",
  "Saudi Arabia": "Arabia Saudí",
  Scotland: "Escocia",
  Senegal: "Senegal",
  Serbia: "Serbia",
  "Sierra Leone": "Sierra Leona",
  Slovakia: "Eslovaquia",
  Slovenia: "Eslovenia",
  "South Africa": "Sudáfrica",
  Spain: "España",
  Sweden: "Suecia",
  Switzerland: "Suiza",
  Togo: "Togo",
  Tunisia: "Túnez",
  Türkiye: "Turquía",
  Ukraine: "Ucrania",
  "United States": "Estados Unidos",
  Uruguay: "Uruguay",
  Uzbekistan: "Uzbekistán",
  Venezuela: "Venezuela",
  Wales: "Gales",
};

export function nationName(nation: string, locale: SeoLocale): string {
  if (!nation) return "";
  return locale === "es" ? (NATION_ES[nation] ?? nation) : nation;
}
